export const LOGIN_STACK = 'LOGIN_STACK';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const PHONE_SCREEN = 'PHONE_SCREEN';
export const SMS_SCREEN = 'SMS_SCREEN';

export const APP_TAB = 'APP_TAB';
export const CARD_STACK = 'CARD_STACK';
export const CARD_LIST_SCREEN = 'CARD_LIST_SCREEN';
export const CARD_DETAIL_SCREEN = 'CARD_DETAIL_SCREEN';
export const TRANSFERS_SCREEN = 'TRANSFERS_SCREEN';
export const PAYMENTS_SCREEN = 'PAYMENTS_SCREEN';
