export const LOGIN_STACK = 'LOGIN_STACK';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const PHONE_SCREEN = 'PHONE_SCREEN';
export const SMS_SCREEN = 'SMS_SCREEN';

export const APP_TAB = 'APP_TAB';

export const CARD_STACK = 'CARD_STACK';
export const CARD_LIST_SCREEN = 'CARD_LIST_SCREEN';
export const CARD_DETAIL_SCREEN = 'CARD_DETAIL_SCREEN';
export const QR_SCREEN = 'QR_SCREEN';

export const TRANSFER_STACK = 'TRANSFER_STACK';
export const CONTACT_FORM_SCREEN = 'CONTACT_FORM_SCREEN';
export const SELECT_CARD_SCREEN = 'SELECT_CARD_SCREEN';
export const SELECT_DOCUMENT_TYPE_SCREEN = 'SELECT_DOCUMENT_TYPE_SCREEN';
export const SELECT_CLIENT_SCREEN = 'SELECT_CLIENT_SCREEN';
export const TRANSFER_FORM_SCREEN = 'TRANSFER_FORM_SCREEN';

export const CONFIRMATION_MODAL = 'CONFIRMATION_MODAL';
export const SUCCESS_MODAL = 'SUCCESS_MODAL';
export const TRANSFER_SUCCESS_MODAL = 'TRANSFER_SUCCESS_MODAL';

export const TRANSFERS_SCREEN = 'TRANSFERS_SCREEN';
export const PAYMENTS_SCREEN = 'PAYMENTS_SCREEN';

export const MOVEMENT_DETAIL_SCREEN = 'MOVEMENT_DETAIL_SCREEN';
